services:
  freetoken-bench:
    extends:
      file: compose.base.yaml
      service: freetoken-bench

    image: ${FREETOKEN_IMAGE}


  freetoken:
    extends:
      file: compose.base.yaml
      service: freetoken

    image: ${FREETOKEN_IMAGE}


volumes:
  free-token-cache: