services:
  freetoken-bench:
    extends:
      file: compose.benchmark.yaml
      service: freetoken-bench

    image: ${FREETOKEN_IMAGE}


  freetoken:
    extends:
      file: compose.base.yaml
      service: freetoken

    image: ${FREETOKEN_IMAGE}
    depends_on:
      freetoken-bench:
        condition: service_completed_successfully

volumes:
  free-token-cache: