services:
  freetoken:
    extends:
      file: compose.base.yaml
      service: freetoken

    build:
      context: .
      dockerfile: Dockerfile
      args:
        CUDA_VERSION: ${CUDA_VERSION:-13.0.3}

    image: ${FREETOKEN_IMAGE:-freetoken-local:latest}

volumes:
  free-token-cache: