---
services:
  faster-whisper:
    extends:
      file: compose.base.yaml
      service: faster-whisper
    
    depends_on:
      whisper-es-converter:
        condition: service_completed_successfully

  whisper-es-converter:
    extends:
      file: compose.converter.yaml
      service: whisper-es-converter

    
volumes:
  # Persistent Faster Whisper configuration and model download cache.
  faster-whisper-config:

  # Persistent converted Whisper model storage.
  faster-whisper-data: