---
services:
  faster-whisper:
    image: lscr.io/linuxserver/faster-whisper:3.5.0-gpu
    container_name: faster-whisper
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ES
      WHISPER_MODEL: turbo
      # WHISPER_MODEL: /data/whisper-large-v3-turbo-es-int8
      # WHISPER_MODEL: tiny-int8
      # WHISPER_MODEL: tiny-int8
      # WHISPER_MODEL: tiny-int8
      # WHISPER_MODEL: tiny-int8
      WHISPER_BEAM: 3
      WHISPER_LANG: es
      #LOCAL_ONLY: #optional
    ports:
      - target: 10300
        published: 10300
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: faster-whisper-config
        target: /config
      - type: volume
        source: faster-whisper-data
        target: /data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
  whisper-es-converter:
    image: python:3.12-slim
    container_name: whisper-es-converter
    environment:
      HF_HUB_CACHE: /hf-cache
    volumes:
      - type: volume
        source: faster-whisper-config
        target: /hf-cache
      - type: volume
        source: faster-whisper-data
        target: /output
    command:
      - /bin/sh
      - -ec
      - |
        if [ -f /output/whisper-large-v3-turbo-es-int8/model.bin ]; then
          echo "El modelo CTranslate2 ya está convertido."
          exit 0
        fi

        python -m pip install --no-cache-dir \
          --index-url https://download.pytorch.org/whl/cpu \
          torch

        python -m pip install --no-cache-dir \
          ctranslate2==4.8.1 \
          transformers==4.56.1 \
          sentencepiece \
          safetensors

        ct2-transformers-converter \
          --model adriszmar/whisper-large-v3-turbo-es \
          --output_dir /output/whisper-large-v3-turbo-es-int8 \
          --copy_files tokenizer.json preprocessor_config.json \
          --quantization int8_float16

        test -f /output/whisper-large-v3-turbo-es-int8/model.bin
        echo "Conversión terminada correctamente."
    restart: "no"
volumes:
  faster-whisper-config:

  faster-whisper-data:
